# Site configuration for mathematics PhD portfolio
url: "https://nischalpi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/GithubPagesIter1" # the subpath of your site, e.g. /blog
title: "Nischal Bhattarai | Mathematics PhD"
description: "Mathematics PhD Student - Specializing in Analysis and Probability"
author: "Nischal Bhattarai"
email: "nbhattarai@tamu.edu"
logo: "/assets/images/profile.jpg"
repository: "NISCHALPI/GithubPagesIter1"
github:
  repository_nwo: "NISCHALPI/GithubPagesIter1"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-scholar
  - jekyll-paginate

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
  load_paths:
    - _sass
    - node_modules

# Theme settings
# For GitHub Pages deployment - use minima for better compatibility:
theme: minima
# Use remote_theme only if you need a specific GitHub Pages theme
# remote_theme: pages-themes/minimal@v0.2.0

# Navigation
header_pages:
  - index.md
  - research.md
  - blog.md
  - teaching.md
  - resources.md
  - contact.md

# Social media
social:
  - platform: github
    user_url: https://github.com/NISCHALPI
  - platform: google_scholar
    user_url: https://scholar.google.com/citations?user=PLACEHOLDER_ID
  - platform: linkedin
    user_url: https://linkedin.com/in/nischal-bhattarai
  - platform: orcid
    user_url: https://orcid.org/PLACEHOLDER_ID
    
# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Math settings - enable MathJax
mathjax: true

# Scholar settings for publications
scholar:
  style: apa
  locale: en
  sort_by: year,month
  order: descending
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"

# Google Analytics
google_analytics: ""

# Exclude files from processing
exclude:
  - README.md
  - DOCUMENTATION.md
  - TODO.md
  - serve.sh
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle
